### ISSUE TITLE
shall we inform you on changes to openpiv? 

### ISSUE THREAD

**Issue by alexlib** [fabrylab/pyTFM#2]
Hi, 

we've updated to 0.23.6 that should work out of box. it has some important fix in the filters, especially for cases with different magnitudes of u,v, components. 

I could realize that we break sometimes your software, so I'd like to see if it's something we can regulate better. 

Regards
Alex

**Comment by AndreasBauerGit** [comment]
Dear Alex,
Thanks for your consideration. You are very welcome to inform us about any significant changes. Currently, we are using  an older version of openpiv without any problems. So you don't need to be concerned to much about breaking anything with updates. But we may update our software to use the newest version of openpiv at some point.  

All the Best, 

Andreas
